[package]
name = "megalodon"
version = "0.13.1"
edition = "2021"
authors = ["Akira Fukushima <h3.poteto@gmail.com>"]
description = "Mastodon and Pleroma API client library for Rust."
license = "MIT"
repository = "https://github.com/h3poteto/megalodon-rs"
homepage = "https://github.com/h3poteto/megalodon-rs"

[package.metadata.docs.rs]
features = ["native-tls", "rustls-tls"]

[features]
default = ["rustls-tls"]
native-tls = [
    "tokio-tungstenite/native-tls",
    "reqwest/native-tls",
    "oauth2/native-tls",
]
rustls-tls = [
    "tokio-tungstenite/rustls-tls-native-roots",
    "reqwest/rustls-tls",
    "oauth2/rustls-tls",
]

[dependencies]
chrono = { version = ">=0.4.25", features = ["serde"] }
async-trait = "0.1.77"
reqwest = { version = ">=0.11.2", features = [
    "json",
    "multipart",
    "stream",
], default-features = false }
tokio = { version = ">=1.28.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["codec"] }
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
url = "2.5.0"
oauth2 = { version = "4.4" }
sha1 = { version = "0.10" }
hex = { version = "0.4" }
tokio-tungstenite = { version = "0.21" }
urlencoding = { version = "2.1" }
thiserror = ">=1.0.23"
futures-util = ">=0.3.28"
rand = "0.8"
regex = ">=1.3.0"
uuid = { version = "1.7", features = ["v4"] }
tracing = "0.1.40"

[dev-dependencies]
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
